FROM maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests -q

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /build/target/nexo-history-template-0.0.1-SNAPSHOT.jar .
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "nexo-history-template-0.0.1-SNAPSHOT.jar"]
