spring:
  application:
    name: History-template-service
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/nexosalud}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/nexosalud}
    user: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "Pre-Flyway state"
    locations: classpath:db/migration
server:
  port: ${MODULE_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,info
